name: enzymatic_sensor
channels:
  - conda-forge
dependencies:
  - python=3.12.5
  - pip=24.2
  - notebook=7.2.1
  - ipywidgets=8.1.4
  - numpy=2.1.0
  - scipy=1.14.0
  - pandas=2.2.2
  - seaborn=0.13.2
  - matplotlib=3.9.2
  - scikit-learn=1.5.1
  - arviz=0.19.0
  - pip:
      - jax==0.4.31
      - jaxlib==0.4.31
      - jaxtyping==0.2.33
      - numpyro==0.15.2
      - equinox==0.11.5
      - blackjax==1.2.3
      - optax==0.2.3
      - graphviz==0.20.3
      - rich==13.8.0
      - pyrcn==0.0.18
      - colorcet==3.1.0
